#' Random number generator for a quadratic function
#'
#' @param n A positive integer
#' @param theta A positive numeric value
#'
#' @returns A vector of random numbers generated by inverse-cdf sampling
#' @export
#'
#' @examples
#' rquad(1000,1)
rquad <- function(n,theta){


  if (!is.numeric(n) | length(n) != 1) {
    stop("n must be a numeric value")
  }

  if (!is.numeric(theta) | length(theta) != 1) {
    stop("theta must be a numeric value")
  }

  if (n <= 0 | n != as.integer(n)){
    stop("n needs to be a positive integer")
  }

  if (theta <= 0){
    stop("theta must be positive")
  }


  U <- runif(n)

  F_x <- function(x){
    return((theta*x^3+3*x+theta+3)/(2*(theta+3)))
  }
  F_eq <- function(x, u) {
    return(F_x(x) - u)
  }

  x <- sapply(U, function(u) {
    uniroot(
      F_eq,
      interval = c(-1, 1),
      u = u
    )$root
  })

  return(x)
}

